version: '3'
services:
    app:
        container_name: dev-nana-ui-kit
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development